### ISSUE TITLE
Add lineClamp utility

### ISSUE THREAD

**Issue by seaneking** [peppercornstudio/satchel#4]
Mixin for required line clamp props

```js
${lineClamp(n)}
```

**Output**
```css
display: -webkit-box;
-webkit-line-clamp: {n};
-webkit-box-orient: vertical;  
overflow: hidden;
```

Supported in all evergreens (with webkits prefix, go figure)
